service: webrivage-aws-typescript

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10

  region: eu-west-1

  stage: ${opt:stage, 'dev'}

  memorySize: 128

functions:
  echo:
    handler: src/handler.echo
